"""
Translate slides.pptx into 6 languages.
Preserves all formatting, only replaces text content.
"""
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from copy import deepcopy
import copy
import os
import shutil

# Translation dictionaries - comprehensive maps of all slide text
TRANSLATIONS = {
    "es": {
        "title": "Bases de Datos para Hackers",
        "footer": "Ronin 48 | Bases de Datos para Hackers",
        "strings": {
            "Databases for Hackers": "Bases de Datos para Hackers",
            "A Ronin 48 Production": "Una Producción de Ronin 48",
            "Ronin 48 | Databases for Hackers": "Ronin 48 | Bases de Datos para Hackers",
            # Section headers
            "Why Hackers Care About Databases": "Por Qué a los Hackers les Importan las Bases de Datos",
            "What Is a Database, Really?": "¿Qué es Realmente una Base de Datos?",
            "The History Tour": "El Recorrido Histórico",
            "The Big Families": "Las Grandes Familias",
            "The Ten Families of Databases": "Las Diez Familias de Bases de Datos",
            "Cloud Database Services": "Servicios de Bases de Datos en la Nube",
            "Markdown as a Database for LLMs": "Markdown como Base de Datos para LLMs",
            "The Security Section": "La Sección de Seguridad",
            "THE SECURITY SECTION": "LA SECCIÓN DE SEGURIDAD",
            "What to Learn Next": "Qué Aprender a Continuación",
            "Questions & Answers": "Preguntas y Respuestas",
            "Q&A": "Preguntas y Respuestas",
            "References": "Referencias",
            "Resources": "Recursos",
            # Opening
            "Every breach you've ever read about ends at a database": "Toda brecha que hayas leído termina en una base de datos",
            "Every breach ends at a database": "Toda brecha termina en una base de datos",
            "The crown jewels are always data": "Las joyas de la corona siempre son datos",
            "You don't need a CS degree": "No necesitas un título en informática",
            "You need a mental map": "Necesitas un mapa mental",
            # What is a database
            "Organized storage": "Almacenamiento organizado",
            "A way to ask questions": "Una forma de hacer preguntas",
            "Filing cabinet vs Spreadsheet vs Database": "Archivador vs Hoja de cálculo vs Base de datos",
            "Table": "Tabla",
            "Row": "Fila",
            "Column": "Columna",
            "Query": "Consulta",
            "Schema": "Esquema",
            "Index": "Índice",
            "CRUD": "CRUD",
            "Create, Read, Update, Delete": "Crear, Leer, Actualizar, Eliminar",
            "Structured vs Unstructured": "Estructurado vs No estructurado",
            # History
            "Flat Files": "Archivos Planos",
            "Hierarchical": "Jerárquico",
            "Network Model": "Modelo de Red",
            "Relational Revolution": "Revolución Relacional",
            "Client-Server Era": "Era Cliente-Servidor",
            "The NoSQL Wave": "La Ola NoSQL",
            "Cloud & NewSQL": "Nube y NewSQL",
            "The Current Edge": "La Frontera Actual",
            "1960s": "Años 60",
            "1970s": "Años 70",
            "1980s": "Años 80",
            "1990s": "Años 90",
            "2000s": "Años 2000",
            "2010s": "Años 2010",
            "2020s": "Años 2020",
            # Families
            "Relational / SQL": "Relacional / SQL",
            "Document Stores": "Almacenes de Documentos",
            "Key-Value Stores": "Almacenes Clave-Valor",
            "Column-Family": "Familia de Columnas",
            "Graph Databases": "Bases de Datos de Grafos",
            "Search Engines": "Motores de Búsqueda",
            "Time-Series": "Series Temporales",
            "Vector Databases": "Bases de Datos Vectoriales",
            "Embedded / Edge": "Embebido / Edge",
            "Data Lakes": "Lagos de Datos",
            "Schema-on-read vs Schema-on-write": "Esquema en lectura vs Esquema en escritura",
            "Use when": "Usar cuando",
            "Security gotcha": "Trampa de seguridad",
            "Products": "Productos",
            # Cloud
            "Shared Responsibility Model": "Modelo de Responsabilidad Compartida",
            "Common Database Ports": "Puertos Comunes de Bases de Datos",
            "What the cloud secures": "Lo que la nube asegura",
            "What YOU secure": "Lo que TÚ aseguras",
            "Common Ports": "Puertos Comunes",
            # LLM/Markdown
            "Markdown files as structured knowledge": "Archivos Markdown como conocimiento estructurado",
            "Obsidian vaults": "Bóvedas de Obsidian",
            "RAG Pipelines": "Pipelines RAG",
            "Embed → Store → Search": "Embeber → Almacenar → Buscar",
            "Data poisoning via tampered documents": "Envenenamiento de datos vía documentos manipulados",
            # Security section
            "SQL Injection: A Success Story": "Inyección SQL: Una Historia de Éxito",
            "The attack surface has EXPANDED": "La superficie de ataque se ha EXPANDIDO",
            "The attack surface has expanded, not shrunk": "La superficie de ataque se ha expandido, no reducido",
            "NoSQL Injection": "Inyección NoSQL",
            "Exposed & Misconfigured Databases": "Bases de Datos Expuestas y Mal Configuradas",
            "Cloud Misconfigurations": "Configuraciones Erróneas en la Nube",
            "Privilege Escalation": "Escalación de Privilegios",
            "Data Lake Security Gaps": "Brechas de Seguridad en Lagos de Datos",
            "Ransomware Targeting Databases": "Ransomware Dirigido a Bases de Datos",
            "Credential Attacks": "Ataques de Credenciales",
            "Supply Chain Attacks": "Ataques a la Cadena de Suministro",
            "LLM/RAG Data Poisoning": "Envenenamiento de Datos LLM/RAG",
            "Insider Threats": "Amenazas Internas",
            "Backup & Snapshot Exposure": "Exposición de Respaldos y Snapshots",
            "Default credentials": "Credenciales por defecto",
            "Connection string leaks": "Fugas de cadenas de conexión",
            "Over-permissioned service accounts": "Cuentas de servicio con permisos excesivos",
            "Lateral movement via DB links": "Movimiento lateral vía enlaces de BD",
            "Unencrypted backups": "Respaldos sin cifrar",
            # xkcd
            "xkcd #327 — Bobby Tables": "xkcd #327 — Bobby Tables",
            # Wrap-up
            "Install PostgreSQL locally": "Instala PostgreSQL localmente",
            "Do one SQLi lab on PortSwigger": "Haz un laboratorio de SQLi en PortSwigger",
            "Browse Shodan for exposed databases": "Busca bases de datos expuestas en Shodan",
            "Read one breach report": "Lee un informe de brecha",
            "Learn your org's database inventory": "Aprende el inventario de BD de tu organización",
            "Databases are where the money is": "Las bases de datos son donde está el dinero",
            "Literally": "Literalmente",
            "Now you know where to look": "Ahora sabes dónde buscar",
            "Databases are where the money is. Literally. Now you know where to look.": "Las bases de datos son donde está el dinero. Literalmente. Ahora sabes dónde buscar.",
            "Next Steps": "Próximos Pasos",
            "Your homework for next week": "Tu tarea para la próxima semana",
        }
    },
    "fr": {
        "title": "Bases de Données pour Hackers",
        "footer": "Ronin 48 | Bases de Données pour Hackers",
        "strings": {
            "Databases for Hackers": "Bases de Données pour Hackers",
            "A Ronin 48 Production": "Une Production Ronin 48",
            "Ronin 48 | Databases for Hackers": "Ronin 48 | Bases de Données pour Hackers",
            "Why Hackers Care About Databases": "Pourquoi les Hackers S'intéressent aux Bases de Données",
            "What Is a Database, Really?": "Qu'est-ce Qu'une Base de Données, Vraiment?",
            "The History Tour": "La Visite Historique",
            "The Big Families": "Les Grandes Familles",
            "The Ten Families of Databases": "Les Dix Familles de Bases de Données",
            "Cloud Database Services": "Services de Bases de Données Cloud",
            "Markdown as a Database for LLMs": "Markdown comme Base de Données pour LLMs",
            "The Security Section": "La Section Sécurité",
            "THE SECURITY SECTION": "LA SECTION SÉCURITÉ",
            "What to Learn Next": "Que Faut-il Apprendre Ensuite",
            "Questions & Answers": "Questions et Réponses",
            "Q&A": "Questions et Réponses",
            "References": "Références",
            "Resources": "Ressources",
            "Every breach you've ever read about ends at a database": "Chaque brèche dont vous avez entendu parler se termine dans une base de données",
            "Every breach ends at a database": "Chaque brèche se termine dans une base de données",
            "The crown jewels are always data": "Les joyaux de la couronne sont toujours les données",
            "You don't need a CS degree": "Pas besoin d'un diplôme en informatique",
            "You need a mental map": "Vous avez besoin d'une carte mentale",
            "Organized storage": "Stockage organisé",
            "A way to ask questions": "Un moyen de poser des questions",
            "Filing cabinet vs Spreadsheet vs Database": "Classeur vs Tableur vs Base de données",
            "Table": "Table",
            "Row": "Ligne",
            "Column": "Colonne",
            "Query": "Requête",
            "Schema": "Schéma",
            "Index": "Index",
            "Create, Read, Update, Delete": "Créer, Lire, Mettre à jour, Supprimer",
            "Structured vs Unstructured": "Structuré vs Non structuré",
            "Flat Files": "Fichiers Plats",
            "Hierarchical": "Hiérarchique",
            "Network Model": "Modèle Réseau",
            "Relational Revolution": "Révolution Relationnelle",
            "Client-Server Era": "Ère Client-Serveur",
            "The NoSQL Wave": "La Vague NoSQL",
            "Cloud & NewSQL": "Cloud et NewSQL",
            "The Current Edge": "La Frontière Actuelle",
            "Relational / SQL": "Relationnel / SQL",
            "Document Stores": "Magasins de Documents",
            "Key-Value Stores": "Magasins Clé-Valeur",
            "Column-Family": "Famille de Colonnes",
            "Graph Databases": "Bases de Données Graphe",
            "Search Engines": "Moteurs de Recherche",
            "Time-Series": "Séries Temporelles",
            "Vector Databases": "Bases de Données Vectorielles",
            "Embedded / Edge": "Embarqué / Edge",
            "Data Lakes": "Lacs de Données",
            "Schema-on-read vs Schema-on-write": "Schéma à la lecture vs Schéma à l'écriture",
            "Use when": "Utiliser quand",
            "Security gotcha": "Piège de sécurité",
            "Products": "Produits",
            "Shared Responsibility Model": "Modèle de Responsabilité Partagée",
            "Common Database Ports": "Ports de Bases de Données Courants",
            "What the cloud secures": "Ce que le cloud sécurise",
            "What YOU secure": "Ce que VOUS sécurisez",
            "Common Ports": "Ports Courants",
            "Markdown files as structured knowledge": "Fichiers Markdown comme savoir structuré",
            "Obsidian vaults": "Coffres Obsidian",
            "RAG Pipelines": "Pipelines RAG",
            "Embed → Store → Search": "Intégrer → Stocker → Chercher",
            "Data poisoning via tampered documents": "Empoisonnement de données via documents falsifiés",
            "SQL Injection: A Success Story": "Injection SQL: Une Réussite",
            "The attack surface has EXPANDED": "La surface d'attaque s'est ÉLARGIE",
            "The attack surface has expanded, not shrunk": "La surface d'attaque s'est élargie, pas réduite",
            "NoSQL Injection": "Injection NoSQL",
            "Exposed & Misconfigured Databases": "Bases de Données Exposées et Mal Configurées",
            "Cloud Misconfigurations": "Mauvaises Configurations Cloud",
            "Privilege Escalation": "Élévation de Privilèges",
            "Data Lake Security Gaps": "Failles de Sécurité des Lacs de Données",
            "Ransomware Targeting Databases": "Ransomware Ciblant les Bases de Données",
            "Credential Attacks": "Attaques de Credentials",
            "Supply Chain Attacks": "Attaques de la Chaîne d'Approvisionnement",
            "LLM/RAG Data Poisoning": "Empoisonnement de Données LLM/RAG",
            "Insider Threats": "Menaces Internes",
            "Backup & Snapshot Exposure": "Exposition des Sauvegardes et Snapshots",
            "Default credentials": "Identifiants par défaut",
            "Connection string leaks": "Fuites de chaînes de connexion",
            "Over-permissioned service accounts": "Comptes de service trop permissifs",
            "Lateral movement via DB links": "Mouvement latéral via liens de BD",
            "Unencrypted backups": "Sauvegardes non chiffrées",
            "xkcd #327 — Bobby Tables": "xkcd #327 — Bobby Tables",
            "Install PostgreSQL locally": "Installez PostgreSQL localement",
            "Do one SQLi lab on PortSwigger": "Faites un labo SQLi sur PortSwigger",
            "Browse Shodan for exposed databases": "Parcourez Shodan pour les BD exposées",
            "Read one breach report": "Lisez un rapport de brèche",
            "Learn your org's database inventory": "Apprenez l'inventaire BD de votre organisation",
            "Databases are where the money is. Literally. Now you know where to look.": "Les bases de données sont là où se trouve l'argent. Littéralement. Maintenant vous savez où chercher.",
            "Next Steps": "Prochaines Étapes",
            "Your homework for next week": "Vos devoirs pour la semaine prochaine",
        }
    },
    "de": {
        "title": "Datenbanken für Hacker",
        "footer": "Ronin 48 | Datenbanken für Hacker",
        "strings": {
            "Databases for Hackers": "Datenbanken für Hacker",
            "A Ronin 48 Production": "Eine Ronin 48 Produktion",
            "Ronin 48 | Databases for Hackers": "Ronin 48 | Datenbanken für Hacker",
            "Why Hackers Care About Databases": "Warum Hacker sich für Datenbanken Interessieren",
            "What Is a Database, Really?": "Was ist eine Datenbank, Wirklich?",
            "The History Tour": "Die Geschichtstour",
            "The Big Families": "Die Großen Familien",
            "The Ten Families of Databases": "Die Zehn Datenbank-Familien",
            "Cloud Database Services": "Cloud-Datenbankdienste",
            "Markdown as a Database for LLMs": "Markdown als Datenbank für LLMs",
            "The Security Section": "Der Sicherheitsabschnitt",
            "THE SECURITY SECTION": "DER SICHERHEITSABSCHNITT",
            "What to Learn Next": "Was als Nächstes Lernen",
            "Questions & Answers": "Fragen und Antworten",
            "Q&A": "Fragen und Antworten",
            "References": "Referenzen",
            "Resources": "Ressourcen",
            "Every breach you've ever read about ends at a database": "Jeder Sicherheitsvorfall endet bei einer Datenbank",
            "Every breach ends at a database": "Jeder Vorfall endet bei einer Datenbank",
            "The crown jewels are always data": "Die Kronjuwelen sind immer Daten",
            "You don't need a CS degree": "Kein Informatikstudium nötig",
            "You need a mental map": "Du brauchst eine mentale Karte",
            "Organized storage": "Organisierter Speicher",
            "A way to ask questions": "Eine Art Fragen zu stellen",
            "Filing cabinet vs Spreadsheet vs Database": "Aktenschrank vs Tabelle vs Datenbank",
            "Table": "Tabelle",
            "Row": "Zeile",
            "Column": "Spalte",
            "Query": "Abfrage",
            "Schema": "Schema",
            "Index": "Index",
            "Create, Read, Update, Delete": "Erstellen, Lesen, Aktualisieren, Löschen",
            "Structured vs Unstructured": "Strukturiert vs Unstrukturiert",
            "Flat Files": "Flache Dateien",
            "Hierarchical": "Hierarchisch",
            "Network Model": "Netzwerkmodell",
            "Relational Revolution": "Relationale Revolution",
            "Client-Server Era": "Client-Server-Ära",
            "The NoSQL Wave": "Die NoSQL-Welle",
            "Cloud & NewSQL": "Cloud und NewSQL",
            "The Current Edge": "Die Aktuelle Grenze",
            "Relational / SQL": "Relational / SQL",
            "Document Stores": "Dokumentenspeicher",
            "Key-Value Stores": "Schlüssel-Wert-Speicher",
            "Column-Family": "Spaltenfamilie",
            "Graph Databases": "Graph-Datenbanken",
            "Search Engines": "Suchmaschinen",
            "Time-Series": "Zeitreihen",
            "Vector Databases": "Vektor-Datenbanken",
            "Embedded / Edge": "Eingebettet / Edge",
            "Data Lakes": "Data Lakes",
            "Schema-on-read vs Schema-on-write": "Schema-beim-Lesen vs Schema-beim-Schreiben",
            "Use when": "Verwenden wenn",
            "Security gotcha": "Sicherheitsfalle",
            "Products": "Produkte",
            "Shared Responsibility Model": "Modell der Geteilten Verantwortung",
            "Common Database Ports": "Gängige Datenbankports",
            "What the cloud secures": "Was die Cloud sichert",
            "What YOU secure": "Was DU sicherst",
            "Common Ports": "Gängige Ports",
            "Markdown files as structured knowledge": "Markdown-Dateien als strukturiertes Wissen",
            "Obsidian vaults": "Obsidian-Tresore",
            "RAG Pipelines": "RAG-Pipelines",
            "Embed → Store → Search": "Einbetten → Speichern → Suchen",
            "Data poisoning via tampered documents": "Datenvergiftung durch manipulierte Dokumente",
            "SQL Injection: A Success Story": "SQL-Injection: Eine Erfolgsgeschichte",
            "The attack surface has EXPANDED": "Die Angriffsfläche hat sich VERGRÖSSERT",
            "The attack surface has expanded, not shrunk": "Die Angriffsfläche hat sich vergrößert, nicht verkleinert",
            "NoSQL Injection": "NoSQL-Injection",
            "Exposed & Misconfigured Databases": "Exponierte und Fehlkonfigurierte Datenbanken",
            "Cloud Misconfigurations": "Cloud-Fehlkonfigurationen",
            "Privilege Escalation": "Privilegien-Eskalation",
            "Data Lake Security Gaps": "Data-Lake-Sicherheitslücken",
            "Ransomware Targeting Databases": "Ransomware gegen Datenbanken",
            "Credential Attacks": "Angriffe auf Anmeldedaten",
            "Supply Chain Attacks": "Lieferkettenangriffe",
            "LLM/RAG Data Poisoning": "LLM/RAG-Datenvergiftung",
            "Insider Threats": "Insider-Bedrohungen",
            "Backup & Snapshot Exposure": "Backup- und Snapshot-Exposition",
            "Default credentials": "Standard-Anmeldedaten",
            "Connection string leaks": "Verbindungsstring-Lecks",
            "Over-permissioned service accounts": "Überprivilegierte Dienstkonten",
            "Lateral movement via DB links": "Laterale Bewegung über DB-Links",
            "Unencrypted backups": "Unverschlüsselte Backups",
            "xkcd #327 — Bobby Tables": "xkcd #327 — Bobby Tables",
            "Install PostgreSQL locally": "PostgreSQL lokal installieren",
            "Do one SQLi lab on PortSwigger": "Ein SQLi-Lab auf PortSwigger machen",
            "Browse Shodan for exposed databases": "Shodan nach exponierten Datenbanken durchsuchen",
            "Read one breach report": "Einen Breach-Report lesen",
            "Learn your org's database inventory": "Das DB-Inventar deiner Organisation kennenlernen",
            "Databases are where the money is. Literally. Now you know where to look.": "Datenbanken sind wo das Geld liegt. Buchstäblich. Jetzt wisst ihr wo ihr suchen müsst.",
            "Next Steps": "Nächste Schritte",
            "Your homework for next week": "Eure Hausaufgabe für nächste Woche",
        }
    },
    "ru": {
        "title": "Базы Данных для Хакеров",
        "footer": "Ronin 48 | Базы Данных для Хакеров",
        "strings": {
            "Databases for Hackers": "Базы Данных для Хакеров",
            "A Ronin 48 Production": "Продукция Ronin 48",
            "Ronin 48 | Databases for Hackers": "Ronin 48 | Базы Данных для Хакеров",
            "Why Hackers Care About Databases": "Почему Хакерам Важны Базы Данных",
            "What Is a Database, Really?": "Что Такое База Данных на Самом Деле?",
            "The History Tour": "Исторический Экскурс",
            "The Big Families": "Большие Семейства",
            "The Ten Families of Databases": "Десять Семейств Баз Данных",
            "Cloud Database Services": "Облачные Сервисы Баз Данных",
            "Markdown as a Database for LLMs": "Markdown как База Данных для LLM",
            "The Security Section": "Раздел Безопасности",
            "THE SECURITY SECTION": "РАЗДЕЛ БЕЗОПАСНОСТИ",
            "What to Learn Next": "Что Изучать Дальше",
            "Questions & Answers": "Вопросы и Ответы",
            "Q&A": "Вопросы и Ответы",
            "References": "Источники",
            "Resources": "Ресурсы",
            "Every breach you've ever read about ends at a database": "Каждая утечка заканчивается в базе данных",
            "Every breach ends at a database": "Каждая утечка заканчивается в базе данных",
            "The crown jewels are always data": "Главная ценность — всегда данные",
            "You don't need a CS degree": "Диплом по информатике не нужен",
            "You need a mental map": "Нужна ментальная карта",
            "Organized storage": "Организованное хранилище",
            "A way to ask questions": "Способ задавать вопросы",
            "Filing cabinet vs Spreadsheet vs Database": "Шкаф с файлами vs Таблица vs База данных",
            "Table": "Таблица",
            "Row": "Строка",
            "Column": "Столбец",
            "Query": "Запрос",
            "Schema": "Схема",
            "Index": "Индекс",
            "Create, Read, Update, Delete": "Создать, Прочитать, Обновить, Удалить",
            "Structured vs Unstructured": "Структурированные vs Неструктурированные",
            "Flat Files": "Плоские Файлы",
            "Hierarchical": "Иерархические",
            "Network Model": "Сетевая Модель",
            "Relational Revolution": "Реляционная Революция",
            "Client-Server Era": "Эра Клиент-Сервер",
            "The NoSQL Wave": "Волна NoSQL",
            "Cloud & NewSQL": "Облако и NewSQL",
            "The Current Edge": "Современный Край",
            "Relational / SQL": "Реляционные / SQL",
            "Document Stores": "Документные Хранилища",
            "Key-Value Stores": "Хранилища Ключ-Значение",
            "Column-Family": "Семейство Столбцов",
            "Graph Databases": "Графовые Базы Данных",
            "Search Engines": "Поисковые Движки",
            "Time-Series": "Временные Ряды",
            "Vector Databases": "Векторные Базы Данных",
            "Embedded / Edge": "Встроенные / Edge",
            "Data Lakes": "Озёра Данных",
            "Schema-on-read vs Schema-on-write": "Схема-при-чтении vs Схема-при-записи",
            "Use when": "Использовать когда",
            "Security gotcha": "Ловушка безопасности",
            "Products": "Продукты",
            "Shared Responsibility Model": "Модель Разделённой Ответственности",
            "Common Database Ports": "Стандартные Порты Баз Данных",
            "What the cloud secures": "Что защищает облако",
            "What YOU secure": "Что защищаете ВЫ",
            "Common Ports": "Стандартные Порты",
            "Markdown files as structured knowledge": "Markdown-файлы как структурированное знание",
            "Obsidian vaults": "Хранилища Obsidian",
            "RAG Pipelines": "RAG-пайплайны",
            "Embed → Store → Search": "Встроить → Сохранить → Искать",
            "Data poisoning via tampered documents": "Отравление данных через подменённые документы",
            "SQL Injection: A Success Story": "SQL-Инъекция: История Успеха",
            "The attack surface has EXPANDED": "Поверхность атаки РАСШИРИЛАСЬ",
            "The attack surface has expanded, not shrunk": "Поверхность атаки расширилась, а не сократилась",
            "NoSQL Injection": "NoSQL-Инъекция",
            "Exposed & Misconfigured Databases": "Открытые и Неправильно Настроенные БД",
            "Cloud Misconfigurations": "Ошибки Конфигурации Облака",
            "Privilege Escalation": "Повышение Привилегий",
            "Data Lake Security Gaps": "Пробелы Безопасности Озёр Данных",
            "Ransomware Targeting Databases": "Шифровальщики Против Баз Данных",
            "Credential Attacks": "Атаки на Учётные Данные",
            "Supply Chain Attacks": "Атаки на Цепочку Поставок",
            "LLM/RAG Data Poisoning": "Отравление Данных LLM/RAG",
            "Insider Threats": "Внутренние Угрозы",
            "Backup & Snapshot Exposure": "Утечка Бэкапов и Снимков",
            "Default credentials": "Стандартные учётные данные",
            "Connection string leaks": "Утечки строк подключения",
            "Over-permissioned service accounts": "Сервисные аккаунты с избыточными правами",
            "Lateral movement via DB links": "Боковое перемещение через связи БД",
            "Unencrypted backups": "Незашифрованные бэкапы",
            "xkcd #327 — Bobby Tables": "xkcd #327 — Bobby Tables",
            "Install PostgreSQL locally": "Установите PostgreSQL локально",
            "Do one SQLi lab on PortSwigger": "Пройдите одну лабу SQLi на PortSwigger",
            "Browse Shodan for exposed databases": "Поищите открытые БД в Shodan",
            "Read one breach report": "Прочитайте один отчёт об утечке",
            "Learn your org's database inventory": "Изучите реестр БД вашей организации",
            "Databases are where the money is. Literally. Now you know where to look.": "Базы данных — это где деньги. Буквально. Теперь вы знаете где искать.",
            "Next Steps": "Следующие Шаги",
            "Your homework for next week": "Домашнее задание на следующую неделю",
        }
    },
    "zh": {
        "title": "黑客的数据库指南",
        "footer": "Ronin 48 | 黑客的数据库指南",
        "strings": {
            "Databases for Hackers": "黑客的数据库指南",
            "A Ronin 48 Production": "Ronin 48 出品",
            "Ronin 48 | Databases for Hackers": "Ronin 48 | 黑客的数据库指南",
            "Why Hackers Care About Databases": "为什么黑客关心数据库",
            "What Is a Database, Really?": "数据库到底是什么？",
            "The History Tour": "历史之旅",
            "The Big Families": "数据库大家族",
            "The Ten Families of Databases": "十大数据库家族",
            "Cloud Database Services": "云数据库服务",
            "Markdown as a Database for LLMs": "Markdown作为LLM的数据库",
            "The Security Section": "安全部分",
            "THE SECURITY SECTION": "安全部分",
            "What to Learn Next": "接下来学什么",
            "Questions & Answers": "问答环节",
            "Q&A": "问答环节",
            "References": "参考文献",
            "Resources": "资源",
            "Every breach you've ever read about ends at a database": "你读到的每一次数据泄露都终结于数据库",
            "Every breach ends at a database": "每次泄露都终结于数据库",
            "The crown jewels are always data": "核心资产永远是数据",
            "You don't need a CS degree": "不需要计算机学位",
            "You need a mental map": "你需要一张思维导图",
            "Organized storage": "有组织的存储",
            "A way to ask questions": "一种提问的方式",
            "Filing cabinet vs Spreadsheet vs Database": "文件柜 vs 电子表格 vs 数据库",
            "Table": "表",
            "Row": "行",
            "Column": "列",
            "Query": "查询",
            "Schema": "模式",
            "Index": "索引",
            "Create, Read, Update, Delete": "创建、读取、更新、删除",
            "Structured vs Unstructured": "结构化 vs 非结构化",
            "Flat Files": "平面文件",
            "Hierarchical": "层次型",
            "Network Model": "网状模型",
            "Relational Revolution": "关系型革命",
            "Client-Server Era": "客户端-服务器时代",
            "The NoSQL Wave": "NoSQL浪潮",
            "Cloud & NewSQL": "云与NewSQL",
            "The Current Edge": "当前前沿",
            "Relational / SQL": "关系型 / SQL",
            "Document Stores": "文档存储",
            "Key-Value Stores": "键值存储",
            "Column-Family": "列族",
            "Graph Databases": "图数据库",
            "Search Engines": "搜索引擎",
            "Time-Series": "时序数据库",
            "Vector Databases": "向量数据库",
            "Embedded / Edge": "嵌入式 / 边缘",
            "Data Lakes": "数据湖",
            "Schema-on-read vs Schema-on-write": "读时模式 vs 写时模式",
            "Use when": "适用场景",
            "Security gotcha": "安全陷阱",
            "Products": "产品",
            "Shared Responsibility Model": "共享责任模型",
            "Common Database Ports": "常见数据库端口",
            "What the cloud secures": "云负责保护的部分",
            "What YOU secure": "你负责保护的部分",
            "Common Ports": "常见端口",
            "Markdown files as structured knowledge": "Markdown文件作为结构化知识",
            "Obsidian vaults": "Obsidian知识库",
            "RAG Pipelines": "RAG管道",
            "Embed → Store → Search": "嵌入 → 存储 → 搜索",
            "Data poisoning via tampered documents": "通过篡改文档实现数据投毒",
            "SQL Injection: A Success Story": "SQL注入：一个成功故事",
            "The attack surface has EXPANDED": "攻击面已经扩大",
            "The attack surface has expanded, not shrunk": "攻击面扩大了，而不是缩小了",
            "NoSQL Injection": "NoSQL注入",
            "Exposed & Misconfigured Databases": "暴露和错误配置的数据库",
            "Cloud Misconfigurations": "云配置错误",
            "Privilege Escalation": "权限提升",
            "Data Lake Security Gaps": "数据湖安全漏洞",
            "Ransomware Targeting Databases": "针对数据库的勒索软件",
            "Credential Attacks": "凭证攻击",
            "Supply Chain Attacks": "供应链攻击",
            "LLM/RAG Data Poisoning": "LLM/RAG数据投毒",
            "Insider Threats": "内部威胁",
            "Backup & Snapshot Exposure": "备份和快照泄露",
            "Default credentials": "默认凭证",
            "Connection string leaks": "连接字符串泄露",
            "Over-permissioned service accounts": "权限过高的服务账户",
            "Lateral movement via DB links": "通过数据库链接横向移动",
            "Unencrypted backups": "未加密的备份",
            "xkcd #327 — Bobby Tables": "xkcd #327 — Bobby Tables",
            "Install PostgreSQL locally": "本地安装PostgreSQL",
            "Do one SQLi lab on PortSwigger": "在PortSwigger做一个SQLi实验",
            "Browse Shodan for exposed databases": "在Shodan上搜索暴露的数据库",
            "Read one breach report": "阅读一份泄露报告",
            "Learn your org's database inventory": "了解你组织的数据库清单",
            "Databases are where the money is. Literally. Now you know where to look.": "数据库就是钱所在的地方。真的。现在你知道该往哪里看了。",
            "Next Steps": "下一步",
            "Your homework for next week": "下周的作业",
        }
    },
    "ko": {
        "title": "해커를 위한 데이터베이스",
        "footer": "Ronin 48 | 해커를 위한 데이터베이스",
        "strings": {
            "Databases for Hackers": "해커를 위한 데이터베이스",
            "A Ronin 48 Production": "Ronin 48 제작",
            "Ronin 48 | Databases for Hackers": "Ronin 48 | 해커를 위한 데이터베이스",
            "Why Hackers Care About Databases": "해커가 데이터베이스에 관심을 갖는 이유",
            "What Is a Database, Really?": "데이터베이스란 정말 무엇인가?",
            "The History Tour": "역사 투어",
            "The Big Families": "대가족들",
            "The Ten Families of Databases": "데이터베이스의 10대 가족",
            "Cloud Database Services": "클라우드 데이터베이스 서비스",
            "Markdown as a Database for LLMs": "LLM을 위한 데이터베이스로서의 Markdown",
            "The Security Section": "보안 섹션",
            "THE SECURITY SECTION": "보안 섹션",
            "What to Learn Next": "다음에 배울 것",
            "Questions & Answers": "질문과 답변",
            "Q&A": "질문과 답변",
            "References": "참고문헌",
            "Resources": "리소스",
            "Every breach you've ever read about ends at a database": "여러분이 읽은 모든 침해 사고는 데이터베이스에서 끝납니다",
            "Every breach ends at a database": "모든 침해는 데이터베이스에서 끝납니다",
            "The crown jewels are always data": "핵심 자산은 항상 데이터입니다",
            "You don't need a CS degree": "컴퓨터 공학 학위는 필요 없습니다",
            "You need a mental map": "멘탈 맵이 필요합니다",
            "Organized storage": "조직화된 저장소",
            "A way to ask questions": "질문하는 방법",
            "Filing cabinet vs Spreadsheet vs Database": "서류함 vs 스프레드시트 vs 데이터베이스",
            "Table": "테이블",
            "Row": "행",
            "Column": "열",
            "Query": "쿼리",
            "Schema": "스키마",
            "Index": "인덱스",
            "Create, Read, Update, Delete": "생성, 읽기, 업데이트, 삭제",
            "Structured vs Unstructured": "정형 vs 비정형",
            "Flat Files": "플랫 파일",
            "Hierarchical": "계층형",
            "Network Model": "네트워크 모델",
            "Relational Revolution": "관계형 혁명",
            "Client-Server Era": "클라이언트-서버 시대",
            "The NoSQL Wave": "NoSQL 물결",
            "Cloud & NewSQL": "클라우드와 NewSQL",
            "The Current Edge": "현재의 최전선",
            "Relational / SQL": "관계형 / SQL",
            "Document Stores": "문서 저장소",
            "Key-Value Stores": "키-값 저장소",
            "Column-Family": "컬럼 패밀리",
            "Graph Databases": "그래프 데이터베이스",
            "Search Engines": "검색 엔진",
            "Time-Series": "시계열",
            "Vector Databases": "벡터 데이터베이스",
            "Embedded / Edge": "임베디드 / 엣지",
            "Data Lakes": "데이터 레이크",
            "Schema-on-read vs Schema-on-write": "읽기 시 스키마 vs 쓰기 시 스키마",
            "Use when": "사용 시기",
            "Security gotcha": "보안 함정",
            "Products": "제품",
            "Shared Responsibility Model": "공동 책임 모델",
            "Common Database Ports": "일반적인 데이터베이스 포트",
            "What the cloud secures": "클라우드가 보호하는 것",
            "What YOU secure": "당신이 보호하는 것",
            "Common Ports": "일반 포트",
            "Markdown files as structured knowledge": "구조화된 지식으로서의 Markdown 파일",
            "Obsidian vaults": "Obsidian 볼트",
            "RAG Pipelines": "RAG 파이프라인",
            "Embed → Store → Search": "임베딩 → 저장 → 검색",
            "Data poisoning via tampered documents": "조작된 문서를 통한 데이터 포이즈닝",
            "SQL Injection: A Success Story": "SQL 인젝션: 성공 사례",
            "The attack surface has EXPANDED": "공격 표면이 확장되었습니다",
            "The attack surface has expanded, not shrunk": "공격 표면은 축소된 것이 아니라 확장되었습니다",
            "NoSQL Injection": "NoSQL 인젝션",
            "Exposed & Misconfigured Databases": "노출되고 잘못 구성된 데이터베이스",
            "Cloud Misconfigurations": "클라우드 구성 오류",
            "Privilege Escalation": "권한 상승",
            "Data Lake Security Gaps": "데이터 레이크 보안 격차",
            "Ransomware Targeting Databases": "데이터베이스를 표적으로 한 랜섬웨어",
            "Credential Attacks": "자격 증명 공격",
            "Supply Chain Attacks": "공급망 공격",
            "LLM/RAG Data Poisoning": "LLM/RAG 데이터 포이즈닝",
            "Insider Threats": "내부자 위협",
            "Backup & Snapshot Exposure": "백업 및 스냅샷 노출",
            "Default credentials": "기본 자격 증명",
            "Connection string leaks": "연결 문자열 유출",
            "Over-permissioned service accounts": "과도한 권한의 서비스 계정",
            "Lateral movement via DB links": "DB 링크를 통한 횡방향 이동",
            "Unencrypted backups": "암호화되지 않은 백업",
            "xkcd #327 — Bobby Tables": "xkcd #327 — Bobby Tables",
            "Install PostgreSQL locally": "PostgreSQL을 로컬에 설치하세요",
            "Do one SQLi lab on PortSwigger": "PortSwigger에서 SQLi 실습 하나 하세요",
            "Browse Shodan for exposed databases": "Shodan에서 노출된 데이터베이스를 검색하세요",
            "Read one breach report": "침해 보고서 하나를 읽으세요",
            "Learn your org's database inventory": "조직의 데이터베이스 인벤토리를 파악하세요",
            "Databases are where the money is. Literally. Now you know where to look.": "데이터베이스가 돈이 있는 곳입니다. 문자 그대로. 이제 어디를 봐야 하는지 아시죠.",
            "Next Steps": "다음 단계",
            "Your homework for next week": "다음 주 숙제",
        }
    },
}


def translate_presentation(src_path, dest_path, lang_code):
    """Copy presentation and translate all text while preserving formatting."""
    # Copy the file first
    shutil.copy2(src_path, dest_path)
    
    # Open the copy
    prs = Presentation(dest_path)
    lang = TRANSLATIONS[lang_code]
    strings = lang["strings"]
    
    # Sort by length (longest first) to avoid partial replacements
    sorted_keys = sorted(strings.keys(), key=len, reverse=True)
    
    # Protected terms that should NEVER be translated
    protected = ["Bobby Tables", "Bobby", "Ronin 48", "xkcd", "OWASP", "SQL", "NoSQL",
                 "PostgreSQL", "MySQL", "MongoDB", "Redis", "DynamoDB", "Cassandra",
                 "Neo4j", "Elasticsearch", "InfluxDB", "SQLite", "DuckDB", "Snowflake",
                 "AWS", "GCP", "Azure", "RDS", "S3", "Athena", "Redshift", "Aurora",
                 "BigQuery", "Spanner", "Cosmos DB", "Synapse", "Firestore",
                 "PortSwigger", "Shodan", "Censys", "TryHackMe", "CVE",
                 "CRUD", "ACID", "CAP", "IAM", "RAG", "LLM", "JSON", "YAML",
                 "https://", "http://", ".com", ".org", ".io"]
    
    def translate_text(text):
        """Replace known strings in text, protecting proper nouns."""
        if not text or not text.strip():
            return text
        # Protect "Bobby Tables" by temporarily replacing it
        PLACEHOLDER = "\x00BOBBYTABLES\x00"
        result = text.replace("Bobby Tables", PLACEHOLDER)
        for key in sorted_keys:
            if key in result:
                result = result.replace(key, strings[key])
        # Restore Bobby Tables
        result = result.replace(PLACEHOLDER, "Bobby Tables")
        return result
    
    def translate_text_frame(tf):
        """Translate paragraph-level text (joining runs) while preserving formatting."""
        for para in tf.paragraphs:
            # First try paragraph-level matching (more accurate)
            full_text = para.text
            if not full_text or not full_text.strip():
                continue
            
            # Check if the full paragraph matches a known string
            translated_full = translate_text(full_text)
            
            if translated_full != full_text and para.runs:
                # If we have a translation, put it all in the first run
                # and clear the rest (preserving first run's formatting)
                if len(para.runs) == 1:
                    para.runs[0].text = translated_full
                else:
                    # Distribute: put translated text in first run, empty others
                    para.runs[0].text = translated_full
                    for run in para.runs[1:]:
                        run.text = ""
            else:
                # Fall back to run-level translation
                for run in para.runs:
                    if run.text and run.text.strip():
                        new_text = translate_text(run.text)
                        if new_text != run.text:
                            run.text = new_text
    
    # Process all slides
    for slide in prs.slides:
        # Process all shapes
        for shape in slide.shapes:
            if shape.has_text_frame:
                translate_text_frame(shape.text_frame)
            # Handle tables
            if shape.has_table:
                for row in shape.table.rows:
                    for cell in row.cells:
                        translate_text_frame(cell.text_frame)
        
        # Process speaker notes
        if slide.has_notes_slide:
            notes_tf = slide.notes_slide.notes_text_frame
            translate_text_frame(notes_tf)
    
    prs.save(dest_path)
    return len(prs.slides)


if __name__ == "__main__":
    src = "/home/hermes/databases-for-hackers/slides.pptx"
    
    languages = {
        "es": "Spanish",
        "fr": "French",
        "de": "German",
        "ru": "Russian",
        "zh": "Chinese (Simplified)",
        "ko": "Korean",
    }
    
    for code, name in languages.items():
        dest = f"/home/hermes/databases-for-hackers/slides_{code}.pptx"
        print(f"Translating to {name} ({code})...", end=" ")
        try:
            count = translate_presentation(src, dest, code)
            size = os.path.getsize(dest)
            print(f"✓ {count} slides, {size/1024:.0f}KB")
        except Exception as e:
            print(f"✗ ERROR: {e}")
    
    print("\nDone!")
